"""
LangGraph workflow for Bharat Trip Planner.

Workflow

START
    │
    ▼
Planner Node
    │
    ▼
Tool Executor
    │
    ▼
Itinerary Generator
    │
    ▼
Budget Estimator
    │
    ▼
Budget Validator
    │
 ┌──┴──────────────┐
 │                 │
 ▼                 ▼
END          Replan Node
                    │
                    ▼
          Itinerary Generator
                    │
                    ▼
           Budget Estimator
                    │
                    ▼
           Budget Validator
"""

from langgraph.graph import END, StateGraph

from backend.state import TripState

from backend.agents import (
    planner_node,
    itinerary_node,
    budget_node,
    replan_node,
)

from backend.config import settings
from backend.mcp_client import mcp_client


# ---------------------------------------------------------
# Tool Executor Node
# ---------------------------------------------------------

def tool_executor_node(state: TripState) -> TripState:
    """
    Executes all tasks generated by Planner Agent.
    """

    tool_results = {}

    for task in state["tasks"]:

        task_id = task.get("id", task["tool"])

        try:

            result = mcp_client.execute(task)

        except Exception as ex:

            result = f"Tool execution failed: {str(ex)}"

        tool_results[task_id] = result

    state["tool_results"] = tool_results

    return state


# ---------------------------------------------------------
# Conditional Router
# ---------------------------------------------------------

def budget_router(state: TripState):

    if state["estimated_cost"] <= state["budget"]:
        return "end"

    if state["retry_count"] >= settings.MAX_RETRIES:
        return "end"

    return "replan"


# ---------------------------------------------------------
# Build Graph
# ---------------------------------------------------------

builder = StateGraph(TripState)

builder.add_node(
    "planner",
    planner_node
)

builder.add_node(
    "tool_executor",
    tool_executor_node
)

builder.add_node(
    "itinerary",
    itinerary_node
)

builder.add_node(
    "budget",
    budget_node
)

builder.add_node(
    "replan",
    replan_node
)

# ---------------------------------------------------------
# Flow
# ---------------------------------------------------------

builder.set_entry_point("planner")

builder.add_edge(
    "planner",
    "tool_executor"
)

builder.add_edge(
    "tool_executor",
    "itinerary"
)

builder.add_edge(
    "itinerary",
    "budget"
)

builder.add_conditional_edges(
    "budget",
    budget_router,
    {
        "end": END,
        "replan": "replan"
    }
)

builder.add_edge(
    "replan",
    "itinerary"
)

graph = builder.compile()